# enable scrolling - buffer size
set -g history-limit 65536
# enable scrolling - mouse
set -g mouse on
# enable scrolling - keyboard
set-window-option -g mode-keys vi
# set terminal color, so no weird DA/DEC private mode reports
set -as terminal-features ",xterm-256color:RGB"
# in copy moad, send to xclip for system keyboard
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -in"
