[[language]]
name = "toml"
file-types = ["toml"]
auto-format = true

[[language]]
name = "nix"
language-servers = ["nil"]

[[language]]
name = "bash"
scope = "source.bash"
file-types = ["sh", "bash"]
formatter = { command = "shfmt", args = ["-i", "4", "-ci"] }

[[language]]
name = "just"
language-servers = [
  "just-lsp",
]

# [[language]]
# name = "html"
# file-types = ["html"]
# formatter = { command = "tidy", args = [
#   "-q",
#   "-indent",
#   "-wrap",
#   "0",
#   "--tidy-mark",
#   "no",
#   "--show-body-only",
#   "auto"
# ] }
# language-servers = ["superhtml"]

[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt", args = ["--edition", "2024"] }
language-servers = [
  "rust-analyzer",
]

[[language]]
name = "python"
auto-format = true
language-servers = [
  { name = "pylsp", except-features = ["format"] },
  "ruff",
]

# [language-server.superhtml]
# command = "superhtml"
# args = ["lsp"]

[language-server.rust-analyzer]
config = { checkOnSave = { command = "clippy" }, cargo = { allFeatures = true } }

[language-server.nil]
command = "nil"

[language-server.pylsp.config.pylsp.plugins]
ruff.enabled = true
autopep8.enabled = false
flake8.enabled = false
mccabe.enabled = false
pycodestyle.enabled = false
pyflakes.enabled = false
pylint.enabled = false
yapf.enabled = false
